export { Button } from './Button'
export { Card } from './Card'
export { Badge } from './Badge'
export { Icon } from './Icon'
export { AnimatedSection } from './AnimatedSection'

/* ── Brand — logo + social/brand icons (not Lucide) ── */
export { Logo } from './Logo'
export type { LogoProps, LogoVariant } from './Logo'
export { SocialIcon } from './SocialIcon'
export type { SocialIconProps, SocialIconName } from './SocialIcon'

/* ── Sections & patterns (Fase 2 — migração do site) ── */
export { WhatWeDontDo } from './WhatWeDontDo'
export type { WhatWeDontDoProps, WhatWeDontDoCard } from './WhatWeDontDo'
export { Problem } from './Problem'
export type { ProblemProps, ProblemColumn } from './Problem'
export { Proof } from './Proof'
export type { ProofProps, ProofCase, ProofTestimonial } from './Proof'
export { WaysToWork } from './WaysToWork'
export type { WaysToWorkProps, Engagement } from './WaysToWork'
export { WhoYouWorkWith } from './WhoYouWorkWith'
export type { WhoYouWorkWithProps } from './WhoYouWorkWith'
export { FinalCTA } from './FinalCTA'
export type { FinalCTAProps } from './FinalCTA'
export { Nav } from './Nav'
export type { NavProps, NavLink } from './Nav'
export { Footer } from './Footer'
export type { FooterProps, FooterColumn, FooterSocial } from './Footer'
export { NetworkBg, NetworkBgV1, NetworkBgV2, NetworkBgV3, TOOLS, EDGES } from './NetworkBg'
export type { NetworkBgProps, ToolNode } from './NetworkBg'
export { Hero, HeroDiagram } from './Hero'
export type { HeroProps, HeroMetric, HeroCTA } from './Hero'
export { HowWeBuildIt } from './HowWeBuildIt'
export { PageLayout } from './PageLayout'
export type { PageLayoutProps } from './PageLayout'
export { BlogCard } from './BlogCard'
export type { BlogCardProps, BlogPostLike, LinkRenderer } from './BlogCard'
export { CaseStudyCard } from './CaseStudyCard'
export type { CaseStudyCardProps, CaseStudyLike, CaseMetricLike, CaseMetricAccent } from './CaseStudyCard'
export { CaseFlow } from './CaseFlow'
export type {
  CaseFlowProps,
  CaseFlowNode,
  CaseFlowEdge,
  CaseFlowNodeTone,
  CaseFlowEdgeTone,
} from './CaseFlow'

/* ── Application / Portal components (client-portal-architecture §11) ── */
export { Skeleton } from './Skeleton'
export type { SkeletonProps } from './Skeleton'
export { ThemeToggle } from './ThemeToggle'
export type { ThemeToggleProps, ColorScheme } from './ThemeToggle'
export { EmptyState } from './EmptyState'
export type { EmptyStateProps } from './EmptyState'
export { Tabs } from './Tabs'
export type { TabsProps, TabItem } from './Tabs'
export { TextField } from './TextField'
export type { TextFieldProps } from './TextField'
export { Select } from './Select'
export type { SelectProps, SelectOption } from './Select'
export { Avatar } from './Avatar'
export type { AvatarProps } from './Avatar'
export { Tooltip } from './Tooltip'
export type { TooltipProps } from './Tooltip'
export { Sparkline } from './Sparkline'
export type { SparklineProps } from './Sparkline'
export { LineChart } from './LineChart'
export type { LineChartProps, LineSeries } from './LineChart'
export { DonutChart } from './DonutChart'
export type { DonutChartProps, DonutSegment } from './DonutChart'
export { BarChart } from './BarChart'
export type { BarChartProps, BarItem } from './BarChart'
export { Gauge } from './Gauge'
export type { GaugeProps, GaugeThresholds } from './Gauge'
export { FunnelChart } from './FunnelChart'
export type { FunnelChartProps, FunnelStage } from './FunnelChart'
export { StatCard } from './StatCard'
export type { StatCardProps, StatDelta } from './StatCard'
export { ChartPanel } from './ChartPanel'
export type { ChartPanelProps, ChartLegendItem } from './ChartPanel'
export { DataTable } from './DataTable'
export type { DataTableProps, DataColumn, DataRow } from './DataTable'
export { Timeline } from './Timeline'
export type { TimelineProps, TimelinePhase, PhaseStatus } from './Timeline'
export { Sidebar } from './Sidebar'
export type { SidebarProps, SidebarItem } from './Sidebar'
export { TopBar } from './TopBar'
export type { TopBarProps } from './TopBar'
export { PageHeader, LastSync } from './PageHeader'
export type { PageHeaderProps, LastSyncProps } from './PageHeader'
